export const mockNews = [
  {
    id: '1',
    name: 'Mas de 5000 juguetes donados!',
    slug: null,
    content:
      '<p>Podemos considerar la ultima campaña de donación juguetes como todo un exito! conseguimos 5234!</p><p>pronto haremos la entrega en escuelas primarias de la zona</p>',
    image: '/images/mockNews/mock_6.jpg',
    user_id: null,
    category_id: null,
    created_at: '2022-03-01T21:55:23.000000Z',
    updated_at: '2022-03-01T21:55:23.000000Z',
    deleted_at: null,
    group_id: null,
  },
  {
    id: '2',
    name: 'Exito en la campaña escolar',
    slug: null,
    content:
      '<p>470 alumnos totalmente equipados para las proxima vuelta a clase &nbsp;📝 💪</p>',
    image: '/images/mockNews/mock_5.jpg',
    user_id: null,
    category_id: null,
    created_at: '2022-03-01T21:54:23.000000Z',
    updated_at: '2022-03-01T21:54:23.000000Z',
    deleted_at: null,
    group_id: null,
  },
  {
    id: '3',
    name: 'Tercer encuentro futbolero ⚽',
    slug: null,
    content:
      '<p>La proxima semana se dara el tercer encuentro de partidos de futbol entre las escuelas secundarias❗❗</p>',
    image: '/images/mockNews/mock_4.jpg',
    user_id: null,
    category_id: null,
    created_at: '2022-02-28T21:55:23.000000Z',
    updated_at: '2022-02-28T21:55:23.000000Z',
    deleted_at: null,
    group_id: null,
  },
  {
    id: '4',
    name: 'Yo me quedo en casa!',
    slug: null,
    content:
      '<p>Te mostramos como acercamos materiales de estudio a los mas necesitados para que puedan seguir con sus estudios pese a la pandemia</p>',
    image: '/images/mockNews/mock_3.jpg',
    user_id: null,
    category_id: 1618,
    created_at: '2022-02-25T19:33:52.000000Z',
    updated_at: '2022-02-25T19:33:52.000000Z',
    deleted_at: null,
    group_id: null,
  },
  {
    id: '5',
    name: 'Solidaridad en pandemia. Contra viento y marea',
    slug: null,
    content:
      '<p>Durante los días de aislamiento preventivo y obligatorio, la continuidad pedagógica en Am-Tema sufrió las consecuencias por la falta de conexión. Es que la zona de La Ñata, ubicada en el Delta de Tigre, representa una de las poblaciones más excluidas de conectividad. No hay cable de internet ni wifi. Incluso, hay familias que comparten un dispositivo entre seis o siete miembros. “Gracias al apoyo de FonBec recibimos un celular, una netbook y una ayuda económica mensual que nos permitió utilizar un módem con un chip de teléfono para conectarnos a Internet y así, poder descargar la tarea de los 48 chicos que concurren a nuestra institución”, explica Espinosa. </p>',
    image: '/images/mockNews/mock_2.jpg',
    user_id: null,
    category_id: 1618,
    created_at: '2022-02-23T19:33:52.000000Z',
    updated_at: '2022-02-23T19:33:52.000000Z',
    deleted_at: null,
    group_id: null,
  },
  {
    id: '6',
    name: 'Por la infancia “Leer y crecer”',
    slug: null,
    content:
      '<p><strong>"Leer y Crecer"</strong> es un proyecto educativo-literario de la Fundación <strong>Somos Más</strong> que surge como respuesta a la carencia de materiales y culturales de 440 niños y niñas que asisten a <strong>tres comedores comunitarios</strong> en el partido de San Miguel, Provincia de Buenos Aires.  El proyecto tiene como misión mejorar sustancialmente las oportunidades de estos niños de relacionarse con los otros, con el mundo, con ellos mismos. ¿Cómo? Garantizándoles, no sólo todo lo necesario para el inicio de clases (mochila completa, guardapolvo, zapatillas), sino también su participación permanente y constante en un programa literario de actividades de vinculación con la lectura.vimos en la provincia de Entre Ríos dando ayuda a los más necesitados haciendo entrega de juguetes y útiles escolares </p>',
    image: '/images/mockNews/mock_1.jpg',
    user_id: null,
    category_id: 1618,
    created_at: '2022-02-19T19:33:52.000000Z',
    updated_at: '2022-02-19T19:33:52.000000Z',
    deleted_at: null,
    group_id: null,
  },
  {
    id: '7',
    name: 'Héroes silenciosos',
    slug: null,
    content:
      '<p>Abanderados es un premio a emprendedores sociales de todo el país dedicados a ayudar a nuestros compatriotas más vulnerables. Es el público mismo el que postula a los candidatos que, previa preselección, son evaluados por un jurado de prestigiosas personalidades. Por último, el público elige entre los ocho finalistas. Los proyectos en los que trabajan estos líderes sociales abarcan campos tan variados como educación, salud, nutrición infantil, discapacidad, contención juvenil, cuidado del ambiente, desarrollo comunitario, acogimiento familiar, reinserción laboral e inclusión a través del deporte y el arte, entre otros. </p>',
    image: '/images/mockNews/mock_7.jpg',
    user_id: null,
    category_id: 1618,
    created_at: '2022-02-19T19:33:52.000000Z',
    updated_at: '2022-02-19T19:33:52.000000Z',
    deleted_at: null,
    group_id: null,
  },
]
